#!/usr/bin/env bash
#xalidli
#!/bin/bash
while IFS=':' read -r username password userid groupid gecos home_dir shell; do
    echo "The user $username is part of the $groupid gang, lives in $home_dir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $userid"
done < /etc/passwd

