#!/usr/bin/env bash
#Xalid baba
for file in *; do    
    if [[ -f "$file" && "$file" == *-* ]]; then
      if [[ "$file" == *-* ]]; then
          echo "${file#*-}"
      else 
	     echo "$file"
      fi
    fi
done
